services:
  mysql:
    image: mysql:8.0
    container_name: flashcard-mysql
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flashcard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flashcard-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - flashcard-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: flashcard-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - flashcard-network
    restart: unless-stopped

networks:
  flashcard-network:
    driver: bridge

volumes:
  mysql_data:
