services:
  mysql:
    image: mysql:8.0
    container_name: flashcard-mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret}
      MYSQL_DATABASE: ${DB_NAME:-flashcards_db}
      MYSQL_USER: ${DB_USER:-flashcard_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-flashcard_secret}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flashcard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER:-flashcard_user}", "-p${DB_PASSWORD:-flashcard_secret}"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcard-backend
    ports:
      - "${BACKEND_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-flashcards_db}
      - DB_USER=${DB_USER:-flashcard_user}
      - DB_PASSWORD=${DB_PASSWORD:-flashcard_secret}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,PATCH,DELETE,OPTIONS}
      - CORS_HEADERS=${CORS_HEADERS:-Content-Type,Authorization}
      - SEED_DATABASE=${SEED_DATABASE:-true}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - flashcard-network
    restart: unless-stopped

networks:
  flashcard-network:
    driver: bridge

volumes:
  mysql_data:
